### ISSUE TITLE
investigate windows unit test failures

### ISSUE THREAD

**Issue by dims** [kubernetes/utils#153]
/kind feature
/help
/good-first-issue

See a log file here https://github.com/dims/utils/runs/576625118?check_suite_focus=true

```
2020-04-10T11:04:24.4738710Z === RUN   TestExecutorWithArgs
2020-04-10T11:04:24.4799121Z ##[error]    TestExecutorWithArgs: exec_test.go:83: expected success, got exec: "/bin/sh": file does not exist
2020-04-10T11:04:24.4803979Z ##[error]    TestExecutorWithArgs: exec_test.go:86: unexpected output: ""
2020-04-10T11:04:24.4804404Z --- FAIL: TestExecutorWithArgs (0.03s)
2020-04-10T11:04:24.4809272Z === RUN   TestTimeout
2020-04-10T11:04:24.4882836Z ##[error]    TestTimeout: exec_test.go:141: expected context deadline exceeded but got exit status 1
2020-04-10T11:04:24.4884120Z --- FAIL: TestTimeout (0.02s)
2020-04-10T11:04:24.4884602Z === RUN   TestSetEnv
2020-04-10T11:04:24.4903444Z ##[error]    TestSetEnv: exec_test.go:150: expected success, got exec: "/bin/sh": file does not exist
2020-04-10T11:04:24.4905427Z ##[error]    TestSetEnv: exec_test.go:153: unexpected output: ""
2020-04-10T11:04:24.4907085Z ##[error]    TestSetEnv: exec_test.go:160: expected success, got exec: "/bin/sh": file does not exist
2020-04-10T11:04:24.4918387Z ##[error]    TestSetEnv: exec_test.go:163: unexpected output: ""
2020-04-10T11:04:24.4936454Z --- FAIL: TestSetEnv (0.00s)
2020-04-10T11:04:24.4936662Z === RUN   TestStdIOPipes
2020-04-10T11:04:24.4937773Z ##[error]    TestStdIOPipes: exec_test.go:190: expected Start() not to error, got: exec: "/bin/sh": file does not exist
2020-04-10T11:04:24.4939120Z ##[error]    TestStdIOPipes: exec_test.go:194: expected StdOut to be 'OUT
2020-04-10T11:04:24.5021977Z         ', got: ''
2020-04-10T11:04:24.5023434Z ##[error]    TestStdIOPipes: exec_test.go:198: expected StdErr to be 'ERR
2020-04-10T11:04:24.5040816Z         ', got: ''
2020-04-10T11:04:24.5060348Z ##[error]    TestStdIOPipes: exec_test.go:202: expected Wait() not to error, got: exec: not started
2020-04-10T11:04:24.5062327Z --- FAIL: TestStdIOPipes (0.00s)
2020-04-10T11:04:24.5063358Z === RUN   ExampleNew_stderrPipe
2020-04-10T11:04:24.5063598Z panic: read |0: file already closed
2020-04-10T11:04:24.5063782Z 
2020-04-10T11:04:24.5064051Z goroutine 29 [running]:
2020-04-10T11:04:24.5064340Z k8s.io/utils/exec_test.ExampleNew_stderrPipe.func1(0x6561c0, 0xc0000c20c8, 0xc000166600)
2020-04-10T11:04:24.5064556Z 	D:/a/utils/utils/exec/stdiopipe_test.go:38 +0x12f
2020-04-10T11:04:24.5064817Z created by k8s.io/utils/exec_test.ExampleNew_stderrPipe
2020-04-10T11:04:24.5065021Z 	D:/a/utils/utils/exec/stdiopipe_test.go:35 +0x1e3
2020-04-10T11:04:24.5065245Z FAIL	k8s.io/utils/exec	0.291s
2020-04-10T11:04:37.3978462Z === RUN   TestTempDir
2020-04-10T11:04:37.3991282Z ##[error]    TestTempDir: dir_test.go:84: remove C:\Users\RUNNER~1\AppData\Local\Temp\prefix-754442531\ONE: The process cannot access the file because it is being used by another process.
2020-04-10T11:04:37.4032620Z --- FAIL: TestTempDir (0.01s)
2020-04-10T11:04:37.4033901Z FAIL
2020-04-10T11:04:37.4034495Z FAIL	k8s.io/utils/temp	0.049s
2020-04-10T11:04:39.5051288Z === RUN   TestTotalTime/Test_with_current_system_time
2020-04-10T11:04:39.5052091Z ##[error]    TestTotalTime/Test_with_current_system_time: trace_test.go:80: Expected total time 0, got 0 
2020-04-10T11:04:39.5052619Z --- FAIL: TestTotalTime (0.00s)
2020-04-10T11:04:39.5052868Z     --- FAIL: TestTotalTime/Test_with_current_system_time (0.00s)
2020-04-10T11:04:39.5055106Z === RUN   TestLogIfLong/When_threshold_is_500_and_msg_2_has_highest_share
2020-04-10T11:04:39.5055615Z ##[error]    TestLogIfLong/When_threshold_is_500_and_msg_2_has_highest_share: trace_test.go:230: Msg "msg2" expected in trace log: 
2020-04-10T11:04:39.5056022Z         
2020-04-10T11:04:39.5056298Z === RUN   TestLogIfLong/When_threshold_is_10_and_msg_3_has_highest_share
2020-04-10T11:04:39.5056772Z ##[error]    TestLogIfLong/When_threshold_is_10_and_msg_3_has_highest_share: trace_test.go:230: Msg "msg3" expected in trace log: 
2020-04-10T11:04:39.5057240Z         
2020-04-10T11:04:39.5057629Z === RUN   TestLogIfLong/When_threshold_is_0_and_all_msg_have_same_share
2020-04-10T11:04:39.5057928Z === RUN   TestLogIfLong/When_threshold_is_20_and_all_msg_1_has_highest_share
2020-04-10T11:04:39.5058149Z --- FAIL: TestLogIfLong (0.00s)
2020-04-10T11:04:39.5058394Z     --- FAIL: TestLogIfLong/When_threshold_is_500_and_msg_2_has_highest_share (0.00s)
2020-04-10T11:04:39.5058664Z     --- FAIL: TestLogIfLong/When_threshold_is_10_and_msg_3_has_highest_share (0.00s)
2020-04-10T11:04:39.5058976Z     --- PASS: TestLogIfLong/When_threshold_is_0_and_all_msg_have_same_share (0.00s)
2020-04-10T11:04:39.5059284Z     --- PASS: TestLogIfLong/When_threshold_is_20_and_all_msg_1_has_highest_share (0.00s)
```

**Comment by sebsoto** [comment]
Been working on this here: https://github.com/kubernetes/utils/compare/master...sebsoto:fix_win_tests

I have one more test to fix, will open a PR when thats done

**Comment by dims** [comment]
thanks @sebsoto
